import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import getCurrentUser from "./actions/getCurrentUser";
import Script from "next/script";
import ToastProvider from "../components/ToastProvider";
import SwrProvider from "../providers/SwrProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieData = await getCookieData();
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar currentUser={currentUser} />
        <ToastProvider />

        <div>
          <SwrProvider>{children}</SwrProvider>
        </div>

        <Script src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a511983808697362b68b0674898209fb&libraries=services,clusterer&autoload=false" />
      </body>
    </html>
  );
}

async function getCookieData() {
  const cookieData = cookies().getAll();
  return new Promise((resolve) =>
    setTimeout(() => {
      resolve(cookieData);
    }, 1000)
  );
}
